name: Android Deploy

on:
  workflow_call:
    inputs:
      changelog:
        required: true
        type: string
        description: "app changelog"
      groups:
        required: false
        type: string
        description: "groups to distribute to"
        default: ""
    secrets:
      PLAYSTORE_SERVICE_ACCOUNT_JSON:
        required: true

jobs:
  android-deploy:
    runs-on: self-hosted
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Download Bundle file
        uses: actions/download-artifact@v4
        with:
          name: BUNDLE
