import {
  CHECK_LIST_EXERCISES,
  TCheckListExerciseItem,
} from '@constants/checklist/checklist';

const CHECK_LIST_SNORING_OPTIONS = [
  CHECK_LIST_EXERCISES.SLEEP_ON_YOUR_SIDE,
  CHECK_LIST_EXERCISES.ELEVATE_YOUR_HEAD,
  CHECK_LIST_EXERCISES.HUMIDITY_OVER_50,
  CHECK_LIST_EXERCISES.NASAL_STRIPS_OR_DIALATORS,
];

const CHECK_LIST_APNEA_OPTIONS = [
  CHECK_LIST_EXERCISES.SLEEP_ON_YOUR_SIDE,
  CHECK_LIST_EXERCISES.ELEVATE_YOUR_HEAD,
  CHECK_LIST_EXERCISES.HUMIDITY_OVER_50,
];

export enum ECheckListType {
  SNORING = 'SNORING',
  APNEA = 'APNEA',
  SNORING_APNEA = 'SNORING_APNEA',
}

const CHECKLIST_OPTIONS: Record<ECheckListType, TCheckListExerciseItem[]> = {
  [ECheckListType.SNORING]: CHECK_LIST_SNORING_OPTIONS,
  [ECheckListType.APNEA]: CHECK_LIST_APNEA_OPTIONS,
  [ECheckListType.SNORING_APNEA]: [
    ...CHECK_LIST_SNORING_OPTIONS,
    ...CHECK_LIST_APNEA_OPTIONS,
  ],
};

export {CHECKLIST_OPTIONS};
